### ISSUE TITLE
Failed to load the atom-ide-ui package

### ISSUE THREAD

**Issue by lednhatkhanh** [facebooknuclide/atom-ide-ui#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [atom-ide-ui](https://github.com/facebooknuclide/atom-ide-ui) package 0.1.11

### Stack Trace

Failed to load the atom-ide-ui package

```
At Cannot find module 'rxjs/bundles/Rx.min.js'

Error: Cannot find module 'rxjs/bundles/Rx.min.js'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.19.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.19.0/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.19.0/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-ide-ui/node_modules/nuclide-commons-atom/feature-config.js:7:27)
    at /packages/atom-ide-ui/node_modules/nuclide-commons-atom/feature-config.js:150:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.19.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.19.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:66:33)
    at _load_featureConfig (/packages/atom-ide-ui/node_modules/nuclide-commons-atom/FeatureLoader.js:16:50)
    at FeatureLoader.load (/packages/atom-ide-ui/node_modules/nuclide-commons-atom/FeatureLoader.js:108:24)
    at /packages/atom-ide-ui/node_modules/atom-ide-ui/index.js:62:17)
    at /packages/atom-ide-ui/node_modules/atom-ide-ui/index.js:79:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.19.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.19.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-ide-ui/node_modules/atom-ide-ui/index-entry.js:26:18)
    at /packages/atom-ide-ui/node_modules/atom-ide-ui/index-entry.js:28:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.19.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
```

### Commands

```
     -0:11.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-ide-ui 0.1.11 
atom-import-cost 0.8.4 
atom-ternjs 0.18.3 
atom-typescript 11.0.6 
autocomplete-module-import 0.1.1 
autocomplete-paths 1.0.5 
busy-signal 1.4.3 
code-peek 1.4.20 
color-picker 2.2.5 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.10 
git-blame 1.2.1 
git-plus 7.9.3 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
intentions 1.1.5 
language-babel 2.70.2 
linter 2.2.0 
linter-eslint 8.2.1 
linter-tslint 1.7.0 
linter-ui-default 1.6.4 
minimap 4.29.6 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.2 
minimap-selection 4.5.0 
pigments 0.40.2 
platformio-ide-terminal 2.5.5 
prettier-atom 0.37.0 
project-manager 3.3.5 
sync-settings 0.8.2 
wakatime 7.0.3 
```

**Comment by hansonw** [comment]
This seems like a corrupt install. Could you delete `/packages/atom-ide-ui` and try installing it again?

**Comment by lednhatkhanh** [comment]
@hansonw 
1. I removed and reinstalled the package, still happens.
2. It only happens in the newest version after the update.

**Comment by hansonw** [comment]
Can you also try removing the apm cache, then uninstalling/reinstalling? It's in ~/.atom/.apm I believe. I can't repro this (tried on multiple machines)

**Comment by lednhatkhanh** [comment]
After remove the package folder and reinstall, the warning went away, thanks @hansonw .
