### ISSUE TITLE
[Diagnostics] Linter reference property causes error

### ISSUE THREAD

**Issue by lloiser** [facebooknuclide/atom-ide-ui#4]
### Issue and Steps to Reproduce

The current [linter](https://github.com/steelbrain/linter) message specification describes a `reference` property. see [linter-message-v2.md](https://github.com/steelbrain/linter/blob/5314924e496fc4efe27e7015fb5d16df38069e88/docs/types/linter-message-v2.md)
It is used to jump to a different location, not where the error occurred.

Apparently this `reference` property causes the diagnostic package (from atom-ide-ui) to throw an error.

Here is a really simple atom plugin to reproduce this. Just unzip and run `apm --dev my-linter-package <insert unzipped folder here>`. Then open any JS file.
[my-linter-package.zip](https://github.com/facebooknuclide/atom-ide-ui/files/1248871/my-linter-package.zip)

The actual problem are these lines here:
https://github.com/facebook/nuclide/blob/26c59fd38f8cc84528f874f5d1ba5c24226d594c/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/services/LinterAdapter.js#L94-L106
Here happens the conversion of the linter message to the diagnostic message. 

(note: this happens really often while writing flow code when using the [flow-ide](https://github.com/steelbrain/flow-ide) package)

### Expected Behavior

At least no error! 
It would be nice if it could display the reference too, but it is not required (at the moment).

### Actual Behavior

The following errors are shown in the dev tools:
```
Warning: There is an internal error in the React performance measurement code. Did not expect componentDidMount timer to start while render timer is still in progress for another instance.
```
```
Uncaught Error: Neither text nor html property defined on message
    at getMessageContent (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/atom-ide-ui/pkg/atom-ide-diagnostics-ui/lib/DiagnosticsTable.js:120:13)
    at diagnostics.map.diagnostic (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/atom-ide-ui/pkg/atom-ide-diagnostics-ui/lib/DiagnosticsTable.js:224:30)
    at Array.map (native)
    at DiagnosticsTable.render (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/atom-ide-ui/pkg/atom-ide-diagnostics-ui/lib/DiagnosticsTable.js:223:40)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:808:34)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:835:34)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:759:36)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:739:10)
    at ReactCompositeComponentWrapper.updateComponent (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:658:12)
    at ReactCompositeComponentWrapper.receiveComponent (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:552:10)
    at Object.receiveComponent (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactReconciler.js:126:22)
    at Object.updateChildren (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactChildReconciler.js:110:25)
    at ReactDOMComponent._reconcilerUpdateChildren (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactMultiChild.js:210:32)
    at ReactDOMComponent._updateChildren (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactMultiChild.js:314:31)
    at ReactDOMComponent.updateChildren (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactMultiChild.js:301:12)
    at ReactDOMComponent._updateDOMChildren (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactDOMComponent.js:941:12)
    at ReactDOMComponent.updateComponent (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactDOMComponent.js:759:10)
    at ReactDOMComponent.receiveComponent (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactDOMComponent.js:717:10)
    at Object.receiveComponent (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactReconciler.js:126:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:761:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:739:10)
    at ReactCompositeComponentWrapper.updateComponent (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:658:12)
    at ReactCompositeComponentWrapper.receiveComponent (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:552:10)
    at Object.receiveComponent (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactReconciler.js:126:22)
    at ReactCompositeComponentWrapper._updateRenderedComponent (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:761:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:739:10)
    at ReactCompositeComponentWrapper.updateComponent (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:658:12)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:566:12)
    at Object.performUpdateIfNecessary (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactReconciler.js:158:22)
    at runBatchedUpdates (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactUpdates.js:151:21)
    at ReactReconcileTransaction.perform (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/Transaction.js:138:20)
    at ReactUpdatesFlushTransaction.perform (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/Transaction.js:138:20)
    at ReactUpdatesFlushTransaction.perform (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactUpdates.js:90:38)
    at Object.flushBatchedUpdates (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactUpdates.js:173:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/Transaction.js:204:25)
    at ReactDefaultBatchingStrategyTransaction.perform (/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/Transaction.js:151:16)
```
```
getMessageContent	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/atom-ide-ui/pkg/atom-ide-diagnostics-ui…:120
diagnostics.map.diagnostic	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/atom-ide-ui/pkg/atom-ide-diagnostics-ui…:224
render	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/atom-ide-ui/pkg/atom-ide-diagnostics-ui…:223
_renderValidatedComponentWithoutOwnerOrContext	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:808
_renderValidatedComponent	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:835
_updateRenderedComponent	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:759
_performComponentUpdate	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:739
updateComponent	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:658
receiveComponent	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:552
receiveComponent	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactReconciler.js:126
updateChildren	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactChildReconciler.js:110
_reconcilerUpdateChildren	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactMultiChild.js:210
_updateChildren	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactMultiChild.js:314
updateChildren	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactMultiChild.js:301
_updateDOMChildren	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactDOMComponent.js:941
updateComponent	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactDOMComponent.js:759
receiveComponent	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactDOMComponent.js:717
receiveComponent	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactReconciler.js:126
_updateRenderedComponent	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:761
_performComponentUpdate	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:739
updateComponent	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:658
receiveComponent	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:552
receiveComponent	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactReconciler.js:126
_updateRenderedComponent	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:761
_performComponentUpdate	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:739
updateComponent	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:658
performUpdateIfNecessary	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactCompositeComponent.js:566
performUpdateIfNecessary	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactReconciler.js:158
runBatchedUpdates	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactUpdates.js:151
perform	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/Transaction.js:138
perform	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/Transaction.js:138
perform	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactUpdates.js:90
flushBatchedUpdates	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactUpdates.js:173
closeAll	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/Transaction.js:204
perform	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/Transaction.js:151
batchedUpdates	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactDefaultBatchingStrategy.…:63
enqueueUpdate	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactUpdates.js:201
enqueueUpdate	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactUpdateQueue.js:25
enqueueSetState	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactUpdateQueue.js:210
ReactComponent.setState	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/react/lib/ReactComponent.js:64
_subscription.stream.subscribe.newState	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/nuclide-commons-ui/bindObservableAsProp…:51
a.__tryOrUnsub	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:43
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:42
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.notifyNext	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:240
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:48
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:116
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:106
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.notifyNext	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:63
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.notifyNext	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:60
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:106
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.debouncedNext	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:148
Eb	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:30
a._execute	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:88
a.execute	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:88
a.flush	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:89
setInterval (async)		
a.requestAsyncId	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:87
a.schedule	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:87
b.schedule	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:90
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:148
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.notifyNext	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:240
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:48
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:116
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.notifyNext	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:60
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:106
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.notifyNext	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:60
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:48
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
observeState	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/redux/lib/createStore.js:237
dispatch	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/redux/lib/createStore.js:186
action	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/nuclide-commons/redux-observable.js:67
dispatch	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/redux/lib/applyMiddleware.js:45
a.__tryOrUnsub	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:43
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:42
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.notifyNext	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:60
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.notifyNext	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:139
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.notifyNext	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:60
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:106
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:48
_processUpdate	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/atom-ide-ui/pkg/atom-ide-diagnostics/li…:237
LinterAdapter._disposables.default.groupBy.mergeMap.subscribe	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/atom-ide-ui/pkg/atom-ide-diagnostics/li…:206
a.__tryOrUnsub	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:43
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:42
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.notifyNext	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:139
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a._tryNext	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:217
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:217
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.notifyNext	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:240
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.notifyNext	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:240
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
p	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:23
a._innerSub	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:239
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:239
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.notifyNext	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:60
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
(anonymous)	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:23
Promise.resolve (async)		
_rxjsBundlesRxMinJs.Observable.defer	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/atom-ide-ui/pkg/atom-ide-diagnostics/li…:215
a._callFactory	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:66
a.tryDefer	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:66
a	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:66
a._subscribe	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:66
b._trySubscribe	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:45
b.subscribe	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:45
b.call	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:238
b.subscribe	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:45
p	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:23
a._innerSub	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:239
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:239
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.notifyNext	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:60
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:48
a._group	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:180
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:179
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
a.notifyNext	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:60
a._next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:61
a.next	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:40
debounced	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/nuclide-commons/debounce.js:45
_dispatchEvents	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/nuclide-commons-atom/text-event.js:267
setImmediate	@	/Users/lloiser/.atom/packages/atom-ide-ui/node_modules/nuclide-commons-atom/text-event.js:251
runCallback	@	timers.js:651
tryOnImmediate	@	timers.js:624
processImmediate	@	timers.js:596
```

### Versions
```
$ atom -v
Atom    : 1.19.3
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
```
$ apm -v
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.10.1
```
* Client OS: mac osx El Capitan (10.11.6)

### Additional Details
* Installed packages (`apm ls --installed`):
```
Dev Packages (1) /Users/lloiser/.atom/dev/packages
└── my-linter-package@0.0.0

Community Packages (29) /Users/lloiser/.atom/packages
├── atom-beautify@0.30.5
├── atom-bpmn@0.0.0 (disabled)
├── atom-ide-ui@0.1.12
├── autocomplete-bash-builtins@0.3.5
├── autocomplete-paths@2.8.0
├── busy-signal@1.4.3 (disabled)
├── docblockr@0.11.0
├── editorconfig@2.2.2
├── file-icons@2.1.11
├── filesize@3.0.0
├── flow-ide@1.8.1
├── git-plus@7.9.3
├── go-debug@1.5.0
├── go-plus@5.5.5
├── go-signature-statusbar@1.2.1 (disabled)
├── go-testrunner@0.0.0
├── highlight-selected@0.13.1
├── hyperclick@0.1.3 (disabled)
├── intentions@1.1.5 (disabled)
├── language-ansi-styles@0.0.1
├── last-cursor-position@0.9.2
├── linter@2.2.0 (disabled)
├── linter-eslint@8.2.1
├── linter-js-standard@3.9.3 (disabled)
├── linter-jsonlint@1.3.0
├── linter-stylelint@4.0.1 (disabled)
├── linter-ui-default@1.6.7 (disabled)
├── project-manager@3.3.5 (disabled)
└── react@0.16.2
```

**Comment by hansonw** [comment]
Oops! Yeah the returned trace in `LinterAdapter` needs to have an empty `text` field (and then it should appear in the UI). We can make that fix (or also happy to accept a PR over at https://github.com/facebook/nuclide)
